name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      POSTGRES_IMAGE: "postgres:11.6-alpine"
      CLAIR_VERSION: "v2.1.7"
      CLAIR_LOCAL_SCAN_IMAGE: "arminc/clair-local-scan"

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build the image
        run: docker build -t $CLAIR_LOCAL_SCAN_IMAGE --build-arg VERSION=$CLAIR_VERSION clair
        
      - name: Run Postgres
        run: |
          docker pull $POSTGRES_IMAGE
          docker run -d --name postgres -e 'PGDATA=/var/lib/postgresql/clair' -e POSTGRES_PASSWORD=password $POSTGRES_IMAGE

      - name: Run Clair
        run: |
          docker run --rm -d --link postgres:postgres -e PGPASSWORD=password $POSTGRES_IMAGE pg_isready -U postgres -h postgres
          docker run -d --name clair --link postgres:postgres $CLAIR_LOCAL_SCAN_IMAGE

      - name: Check
        run: |
          ./check.sh
          docker logs clair

      - name: Tag clair-db image
        run: |
          docker stop clair
          docker stop postgres
          docker commit postgres arminc/clair-db:$(date +%Y-%m-%d)
          docker tag arminc/clair-db:$(date +%Y-%m-%d) arminc/clair-db:latest
          docker tag $CLAIR_LOCAL_SCAN_IMAGE ${CLAIR_LOCAL_SCAN_IMAGE}:${CLAIR_VERSION}_${GITHUB_SHA}
          docker images
