name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      POSTGRES_IMAGE: "postgres:11.6-alpine"
      CLAIR_VERSION: "v2.1.7"
      CLAIR_LOCAL_SCAN_IMAGE: "tim707/clair-local-scan"

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build the image
        run: docker build -t $CLAIR_LOCAL_SCAN_IMAGE --build-arg VERSION=$CLAIR_VERSION clair
        
      - name: Run Postgres
        run: |
          docker pull $POSTGRES_IMAGE
          docker run -d --name postgres -e 'PGDATA=/var/lib/postgresql/clair' -e POSTGRES_PASSWORD=password $POSTGRES_IMAGE
      - name: Run Clair
        run: |
          docker run --rm -d --link postgres:postgres -e PGPASSWORD=password $POSTGRES_IMAGE pg_isready -U postgres -h postgres
          docker run -d --name clair --link postgres:postgres $CLAIR_LOCAL_SCAN_IMAGE
#      - name: Check
#        run: |
#          ./check.sh
#          docker logs clair
      - name: Tag clair-db image
        run: |
          docker stop clair
          docker stop postgres
          docker commit postgres tim707/clair-db:$(date +%Y-%m-%d)
          docker tag tim707/clair-db:$(date +%Y-%m-%d) tim707/clair-db:latest
          docker tag $CLAIR_LOCAL_SCAN_IMAGE ${CLAIR_LOCAL_SCAN_IMAGE}:${CLAIR_VERSION}_${GITHUB_SHA}
          docker images
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push images
        run: |
          docker push ${CLAIR_LOCAL_SCAN_IMAGE}:${CLAIR_VERSION}_${GITHUB_SHA}
          docker push $CLAIR_LOCAL_SCAN_IMAGE:latest
          docker push tim707/clair-db:$(date +%Y-%m-%d)
          docker push tim707/clair-db:latest
